### ISSUE TITLE
 When no email id is entered in the To field on the Send to a friend page, then a notice should be set.

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/send-a-friend-addon#19]
An alert box is coming when no email id is entered in the To field on the Send to a friend page. It is different than the WordPress or WooCommerce plugin format. 

http://screencast.com/t/oOV6eDYMIi

**Comment by apeksha10** [comment]
This is a very old issue

None of the clients has come up with this issue

Hence I have closed this issue
