### ISSUE TITLE
When 0 bookings are left and when I try to send it to a friend, there is no notice displayed

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/send-a-friend-addon#38]
Reference to https://github.com/TycheSoftwares/send-a-friend-addon/issues/15
When there are 0 bookings left for a product and I try to send it to a friend, there should be a notice displayed saying that 'Email could not be sent as all the items have been fully booked.' But there is only a statement displayed: http://screencast.com/t/mPcetVC2HC

**Comment by apeksha10** [comment]
This is a very old issue

None of the clients has come up with this issue

Hence I have closed this issue
