### ISSUE TITLE
The notice 'The date Mon, Nov 23, 2015 is past today. Please select another date' is displayed even when the date is available for booking

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/send-a-friend-addon#57]
I had placed an order for 23rd Nov till 25th Nov (23rd Nov is the current date). Clicking on the Book another space, I got the notice: 'The date Mon, Nov 23, 2015 is past today. Please select another date' on the product page, whereas 23rd Nov is enabled for booking. If I open the calendar 23rd Nov is enabled for booking.

The notice should not come when the current date is still available for booking as it may result in underbooking even when the date is available.

http://screencast.com/t/nvphJpuFW

http://screencast.com/t/apLgOIVPPoP

**Comment by apeksha10** [comment]
This is a very old issue

None of the clients has come up with this issue

Hence I have closed this issue
