### ISSUE TITLE
The availability of the date is coming incorrect on the Order Received page with attribute level lockout

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/send-a-friend-addon#74]
I have attribute level lockout for a product with multiple days booking. The attribute lockout is set as 6. And date lockout is set as 11.

After placing an order for one quantity, the availability on the order received page and in the email sent via Send to a Friend button is coming as 10 instead of 5. http://prntscr.com/evxi6o & http://prntscr.com/evxiop

When opening the product via the button to Book in from the email, the availability for the date is coming as 5, which is correct. http://prntscr.com/evxiir

Note: This will also be the case for variation lockout.

**Comment by apeksha10** [comment]
This is a very old issue

None of the clients has come up with this issue

Hence I have closed this issue
